{% set name = "emi" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{version}}

source:
  path: ./
  # url: 
  # sha256:

build:
  number: 0

test: 
  commands:
    - $PREFIX/bin/hk

requirements:
  build:
    - cmake
    - make
    - gxx  # Use `clang` on macOS

  host: 
    - gxx
    - libgcc-ng
    - libstdcxx-ng
  
  run:
    - gxx
    - libgcc-ng
    - libstdcxx-ng

about:
  home: https://biophys-turin.github.io
  summary: "A simple tool to estimate mutual information."
  license: GPL-2.0-or-later
  description: |
    Effiecnt tool to estimate mutual information
  extra:
    recipe-maintainers:
      - fvalle1
      - LeonardoAgasso
      - biophys-turin