{% set name = "emi" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{version}}

source:
  # path: ./
  url: https://github.com/BioPhys-Turin/EfficientMutualInformation/archive/refs/tags/0.1.0.tar.gz 
  sha256: 492641e36e659d7fc6ec0466649aae85b01dfb8a187606a937e793f2909aa3c8

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - gxx  # Use `clang` on macOS

  host: 
    - gxx
    - libgcc
    - libstdcxx
  
  run:
    - gxx
    - libgcc
    - libstdcxx

test: 
  commands:
    - $PREFIX/bin/hk

about:
  home: https://biophys-turin.github.io
  summary: "A simple tool to estimate mutual information."
  license: GPL-2.0-or-later
  license_file: LICENSE
  description: |
    Effiecnt tool to estimate mutual information

extra:
  recipe-maintainers:
    - fvalle1
    - LeonardoAgasso
