context: {}
package:

  name: emi
  version: 0.1.0

source:
  # path: ./
  url: https://github.com/BioPhys-Turin/EfficientMutualInformation/archive/refs/tags/{{ version }}.tar.gz

build:
  number: 0
  script_env:
    CXXFLAGS: "-std=c++14 -O3 -Wall -Wextra -Wpedantic -Werror"

test:
  commands:
    - hk --help

requirements:
  build:
    - cmake
    - make
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}

  run:

about:
  home: https://biophys-turin.github.io
  summary: A simple tool to estimate mutual information.
  license: MIT

