{% set name = "emi" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{version}}

source:
  url: https://github.com/BioPhys-Turin/EfficientMutualInformation/archive/refs/tags/{{ version }}.tar.gz 
  sha256: 1e64bef7f56a3c02a96b0e89ebc91706cf305471ce352766e9c7eb89ce5a3aa6

build:
  number: 0
  skip: True  # [win or osx]

requirements:
  build:
    - cmake
    - make
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  run:

test: 
  commands:
    - hk --help

about:
  home: https://biophys-turin.github.io
  summary: "A simple tool to estimate mutual information."
  license: GPL-2.0-or-later
  license_file: LICENSE
  description: |
    Effiecnt tool to estimate mutual information

extra:
  recipe-maintainers:
    - fvalle1
    - LeonardoAgasso
