context: {}
package:

  name: emi
  version: 1.0.0

source:
  path: ./

build:
  number: 0
  script_env:
    CXXFLAGS: "-std=c++14 -O3 -Wall -Wextra -Wpedantic -Werror"

test:
  commands:
    - $PREFIX/bin/hk

requirements:
  build:
    - cmake
    - make
    - gxx>=13.3.0  # Use `clang` on macOS

  host: 
    - gxx>=13.3.0
    - libgcc-ng
  
  run:
    - libgcc-ng

about:
  home: https://biophys-turin.github.io
  summary: A simple tool to estimate mutual information.
  license: MIT

